export const coursework = [
  {
    id: "alnarp",
    title: "Alnarp as a food-oriented living lab",
    course: "Foodscapes 2 · FS0008",
    format: "Individual proposal",
    summary: "Exploring how campus landscapes, research facilities and food initiatives could become a shared setting for learning, production and well-being.",
    approach: "I combined a literature review, campus observations and stakeholder mapping to propose connections between Alnarp’s existing food-related spaces and activities.",
    insight: "The proposal links production, conservation, education and community engagement. It considers the spatial, administrative and collaborative changes needed for implementation.",
    tags: ["Living labs", "Stakeholder mapping"],
    url: "https://drive.google.com/file/d/1gqKvzLjg4SkxTq7PlmLJ-5qSeSFD7Rzt/view?usp=drive_link",
  },
  {
    id: "food-planning",
    title: "Feeding the Billions",
    course: "Food Planning · February 2024",
    format: "Group proposal",
    summary: "A proposed food strategy for India connecting hunger reduction, healthy diets and food-waste prevention through local food societies.",
    role: "My contribution: stakeholder engagement, strategic framework and implementation planning.",
    approach: "Our group proposed food societies at panchayat level to connect food collection, redistribution, resource recovery, small enterprises and education, supported by national and state institutions.",
    insight: "The strategy sets an academic ambition for 2040. It is a planning proposal, not an adopted government policy or a record of implemented outcomes.",
    team: "Sonali Basnayaka, Henaka Kulathilake, Tomas Wahlstedt and Goutham Nidhi.",
    tags: ["Food strategy", "Implementation planning"],
    url: "https://drive.google.com/file/d/1BFRcvPEXgW2zcJIy0vFRs7NX5yikj-tq/view?usp=drive_link",
  },
  {
    id: "food-waste",
    title: "Food waste: is urban agriculture a solution?",
    course: "Urban Agriculture & Social Interactions · LK0395",
    format: "Individual article",
    summary: "A popular-science exploration of how growing food closer to people can support waste prevention, local knowledge and nutrient cycling.",
    approach: "I brought together evidence on food loss and waste with examples of urban agriculture, household practices and resource recovery, translating the topic for a wider audience.",
    insight: "Urban agriculture is considered one part of a broader response. Its contribution depends on scale, growing and storage practices, policy support and sustained participation.",
    tags: ["Science communication", "Circular food systems"],
    url: "https://drive.google.com/file/d/1a4THQ3_7BFb57mVUyF91roK_bt2WDiPX/view?usp=drive_link",
  },
  {
    id: "midori",
    title: "MIDORI: a critical assessment",
    course: "Food Planning · FS0002",
    format: "Individual assessment",
    summary: "Examining Japan’s sustainable food-system strategy through technology access, stakeholder participation and the relationship between people and place.",
    approach: "I critically assessed the strategy’s emphasis on innovation and participation, considering adoption barriers, rural–urban relationships, cultural continuity and consumer affordability.",
    insight: "The assessment argues for practical support for producers and a meaningful community role, with spatial planning and local production helping connect national ambitions to everyday food systems.",
    tags: ["Policy analysis", "Inclusive transitions"],
    url: "https://drive.google.com/file/d/14f5K5XaigMIALknBaY6A-XFmMQisstzY/view?usp=drive_link",
  },
  {
    id: "terroir",
    title: "Terroir of Taste",
    course: "Foodscapes 1",
    format: "Individual study",
    summary: "A comparative exploration of Sweden and Kerala, asking how landscape, agriculture and cultural traditions shape the way food is experienced.",
    approach: "I used literature and examples of fruit, vegetables and dairy to explore relationships between environment, food production and culinary culture across the two regions.",
    insight: "The study treats taste as a connection between place and cultural experience. It is a literature-based comparison, not a controlled sensory experiment.",
    tags: ["Food culture", "Landscape comparison"],
    url: "https://drive.google.com/file/d/10WLwi_q7uHeMZlNzLGQnWpyYQJ3SHgyo/view?usp=drive_link",
  },
  {
    id: "tsuruoka",
    title: "Tsuruoka: a city as a living lab",
    course: "Foodscapes 2 · AESOP assignment",
    format: "Individual case study",
    summary: "Reading a Japanese city’s food culture through heirloom crops, culinary knowledge, food education and the communities that keep them in use.",
    approach: "I examined local initiatives such as crop preservation, cooking workshops and recipe archives, alongside challenges including farming succession and cultural change.",
    insight: "The case study uses a city-wide living lab as an interpretive lens for shared learning and collaboration, rather than claiming a separate formal designation.",
    tags: ["Culinary heritage", "Community learning"],
    url: "https://drive.google.com/file/d/1RD5mfTjvvBFzY3PhMJiLUnaUq8skuCcn/view?usp=drive_link",
  },
];
